version: '3'

services:
#wordpress and php-fpm
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file:
      - ./.env
    volumes:
      - database:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - ./.env
    volumes:
      - /home/colonel/data:/var/hjrifi.ma
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    volumes:
      - /home/colonel/data:/var/hjrifi.ma
  
volumes:
  database:
  # wordpress:
