version: '3'


services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file:
      - ./.env
    networks:
      - jrifi_net
    volumes:
      - db-mariadb:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    networks:
      - jrifi_net
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - ./.env
    volumes:
      - db-wordpress:/var/hjrifi.ma/
  ftp-server:
    depends_on:
      - wordpress
    networks:
      - jrifi_net
    ports :
      - "21:21"
      - "40000-40100:40000-40100"
    container_name: ftp-server
    build: ./requirements/FTP_server/
    restart: always
    volumes:
      - db-wordpress:/data/db_ftp
  adminer:
    depends_on:
      - mariadb
    networks:
      - jrifi_net
    container_name: adminer
    build: ./requirements/adminer/
    restart: always
    volumes:
      - db-adminer:/var/adminer
  redis:
    depends_on:
      - mariadb
      - wordpress
    networks:
      - jrifi_net
    container_name: redis
    build: ./requirements/redis/
    restart: always
  website :
    networks:
      - jrifi_net
    container_name: website
    build: ./requirements/website/
    restart : always
    volumes:
      - db-website:/var/hjrifi.ma/
    ports:
      - "3000:3000"
  nginx:
    depends_on:
      - wordpress
      - adminer
    networks:
      - jrifi_net
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    volumes:
      - db-wordpress:/var/hjrifi.ma/
      - db-adminer:/var/adminer

  

volumes:
  db-website:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/website
  db-mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mysql
  db-wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-adminer:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/adminer
networks:
  jrifi_net:
