version: '3'


services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file:
      - ./.env
    networks:
      - jrifi_net
    volumes:
      - db-mariadb:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    networks:
      - jrifi_net
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - ./.env
    volumes:
      - db-wordpress:/var/hjrifi.ma
  adminer:
    depends_on:
      - mariadb
    networks:
      - jrifi_net
    container_name: adminer
    build: ./requirements/adminer/
    restart: always
    volumes:
      - db-adminer:/var/adminer
  nginx:
    depends_on:
      - wordpress
      - adminer
    networks:
      - jrifi_net
    container_name: nginx
    build: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    volumes:
      - db-wordpress:/var/hjrifi.ma/
      - db-adminer:/var/adminer
  

volumes:
  db-mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hjrifi/data/mysql
  db-wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hjrifi/data/wordpress
  db-adminer:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hjrifi/data/adminer
networks:
  jrifi_net:
